# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-26 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=256, verbose_name='Russian title')),
                ('title_en', models.CharField(max_length=256, verbose_name='English title')),
                ('article_ru', models.TextField(verbose_name='Russian article')),
                ('article_en', models.TextField(verbose_name='English article')),
                ('published', models.DateField(blank=True, null=True, verbose_name='Publication date')),
                ('likes', models.IntegerField(default=0, verbose_name='likes')),
            ],
            options={
                'verbose_name_plural': 'News',
                'verbose_name': 'News',
            },
        ),
    ]
