# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-27 16:58
from __future__ import unicode_literals

import apps.core.models
import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Name')),
                ('file', models.FileField(null=True, upload_to=apps.core.models.BaseModel.file_upload_path, verbose_name='File')),
                ('category', models.CharField(blank=True, choices=[('music', 'Music'), ('gtp', 'Guitar PRO'), ('text', 'Text'), ('video', 'Video')], default='music', max_length=255, null=True, verbose_name='Category')),
            ],
            options={
                'verbose_name': 'File',
                'verbose_name_plural': 'Files',
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Name')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='Year')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique_with=('name',), verbose_name='Slug')),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.core.models.BaseModel.file_upload_path, verbose_name='Image')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('file', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='music.File', verbose_name='File')),
            ],
            options={
                'verbose_name': 'Track',
                'verbose_name_plural': 'Tracks',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='TrackFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Sort order')),
                ('file', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_tracks', to='music.File', verbose_name='File')),
                ('track', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extra_files', to='music.Track', verbose_name='Track')),
            ],
            options={
                'verbose_name': 'Track File',
                'verbose_name_plural': 'Track Files',
                'ordering': ('sort_order',),
            },
        ),
    ]
