# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-05 12:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='preview',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Preview'),
        ),
        migrations.AlterField(
            model_name='track',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='music.File', verbose_name='File'),
        ),
    ]
