# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-29 19:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_track_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='track',
            options={'ordering': ('-year', 'name'), 'verbose_name': 'Track', 'verbose_name_plural': 'Tracks'},
        ),
    ]
