# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-10 05:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20180310_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='category',
            field=models.CharField(blank=True, choices=[('music', 'Music'), ('demo', 'Demo'), ('gtp', 'Guitar PRO'), ('text', 'Text'), ('video', 'Video')], default='music', max_length=255, null=True, verbose_name='Category'),
        ),
    ]
