# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-03 12:09
from __future__ import unicode_literals

import apps.core.models
from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_auto_20180330_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='image_thumbnail',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=apps.core.models.BaseModel.file_upload_path),
        ),
        migrations.AlterField(
            model_name='track',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=apps.core.models.BaseModel.file_upload_path, verbose_name='Image'),
        ),
    ]
