# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-01 14:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_mp3', models.URLField(blank=True, max_length=256, verbose_name='Audio File URL (MP3)')),
                ('file_ogg', models.URLField(blank=True, max_length=256, verbose_name='Audio File URL (OGG)')),
                ('file_wav', models.URLField(blank=True, max_length=256, verbose_name='Audio File URL (WAV)')),
                ('version', models.CharField(choices=[('gtp', 'GuitarPro version'), ('rec', 'Recorded version'), ('dem', 'Demo version'), ('aco', 'Acoustic version'), ('ins', 'Instrumental version'), ('liv', 'Live version'), ('oth', 'Other version')], default=('gtp', 'GuitarPro version'), max_length=3, verbose_name='Audio Type')),
                ('main_priority', models.BooleanField(default=False, verbose_name='Main priority')),
            ],
        ),
        migrations.CreateModel(
            name='AudioTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(default='Dendy Not Dead', max_length=128, verbose_name='Artist')),
                ('track_name', models.CharField(max_length=256, verbose_name='Track Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('lyrics', models.TextField(blank=True, null=True, verbose_name='Lyrics')),
                ('published', models.DateField(blank=True, null=True, verbose_name='Publication date')),
                ('gtp_file', models.FileField(blank=True, null=True, upload_to='', verbose_name='GuitarPro File')),
                ('youtube_link', models.URLField(blank=True, null=True, verbose_name='YouTube link')),
                ('likes', models.IntegerField(default=0, verbose_name='likes')),
            ],
        ),
        migrations.AddField(
            model_name='audiofile',
            name='parent_track',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='audiofiles.AudioTrack', verbose_name='Related Audio Track'),
        ),
    ]
