# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-01 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiofiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiotrack',
            name='gtp_file',
            field=models.FileField(blank=True, null=True, upload_to='gtp', verbose_name='GuitarPro File'),
        ),
    ]
