# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-26 07:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WallMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=128, verbose_name='Message')),
                ('published', models.DateField(auto_now=True, null=True, verbose_name='Publication date')),
                ('session_id', models.CharField(max_length=512, verbose_name='Session ID')),
            ],
        ),
    ]
